#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libp11
Version  : 0.4.6
Release  : 1
URL      : https://github.com/OpenSC/libp11/releases/download/libp11-0.4.6/libp11-0.4.6.tar.gz
Source0  : https://github.com/OpenSC/libp11/releases/download/libp11-0.4.6/libp11-0.4.6.tar.gz
Summary  : libp11
Group    : Development/Tools
License  : LGPL-2.1
BuildRequires : pkgconfig(libcrypto)
BuildRequires : sed

%description
Libp11 example code
===================
This directory contains some example code how to use libp11.
Feel free to use this code in any way, it is public domain,
not copyrighted.

%prep
%setup -q -n libp11-0.4.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1496644950
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1496644950
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/include/libp11.h
/usr/lib64/engines/libpkcs11.so
/usr/lib64/engines/pkcs11.so
/usr/lib64/libp11.so
/usr/lib64/libp11.so.2
/usr/lib64/libp11.so.2.4.6
/usr/lib64/pkgconfig/libp11.pc
/usr/share/doc/libp11/NEWS

